import numpy as np
a = np.array([1,2,3,4])
print(a)
print(np.zeros((2,3)))
print(np.ones((2,3)))
b=np.arange(0,10,2)
print(b)
d=np.arange(6)
print(d)
c=d.reshape((2,3))
print(c)
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(2,3))
x=np.random.randint(0,10)
print(x)
y=np.random.randint(0,100,size=5)
print(y)
z=np.random.randint(0,100,size=(3,3))
print(z)
OTP=np.random.randint(000000,999999)
print(OTP)


